services:
  - type: web
    name: esf-thamara
    env: node
    # For√ßa o uso do NPM para evitar conflito com Yarn
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: esf-db
          property: connectionString