services:
  - type: web
    name: esf-thamara-backend
    env: node
    plan: free
    repo: https://github.com/IvanM1999/ESF-Thamara
    branch: main
    buildCommand: 'cd backend && npm install'
    startCommand: 'cd backend && node server.js'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: esf-thamara-db
          type: postgresql
  - type: 
    name: esf-thamara-frontend
    env: static
    repo: https://github.com/IvanM1999/ESF-Thamara
    branch: main
    publishPath: public
databases:
  - type: postgresql
    name: esf-thamara-db
    plan: starter
