services:
  - type: web
    name: esf-thamara-backend
    env: node
    plan: free
    repo: https://github.com/IvanM1999/ESF-Thamara
    branch: main
    buildCommand: 'cd backend && npm install'
    startCommand: 'cd backend && node server.js'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: esf-thamara-db
          property: connectionString

  - type: web
    name: esf-thamara-frontend
    env: static
    plan: free
    repo: https://github.com/IvanM1999/ESF-Thamara
    branch: main
    buildCommand: 'cd frontend && npm install && npm run build'
    staticPublishPath: frontend/public

databases:
  - name: esf-thamara-db
    plan: starter
